
n=eval(input("Masukkan List: "))
listset=set(n)
print(f"List sebelum dikonversi {n}")
print(f"Setelah dikonversi {listset}")
k=set(eval(input("Masukkan Set: ")))
setlist=list(k)
print(f"Set sebelum dikonversi {k}")
print(f"Setelah dikonversi {setlist}")
m=eval(input("Masukkan tuple: "))
tupleset=set(m)
print(f"Tuple sebelum dikonversi {m}")
print(f"Setelah dikonversi {tupleset}")
settuple=tuple(k)
print(f"Set sebelum dikonversi {k}")
print(f"Setelah dikonversi {settuple}")